config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :comments
  mount Ckeditor::Engine => '/ckeditor'

  get 'targets/index'

  get 'gender_count/:id' => 'projects#gender_count'

  get '*path', to: 'home#setup',
    constraints: ProjectConstraints.new

  resource :project do
    get :dashboard
    get :status_config
    get :reporting_table
  end

  resources :households do
    resources :income_sources
    resources :people do
      resources :follow_ups
      resources :service_instances
      resources :timelines, only: [:index]
    end
    post :finalize, on: :member
  end

  resources :indicators do
    resources :indicator_details
    resources :targets do
      collection do
        get :edit_multiple
        post :create_multiple
        put :update_multiple
      end
    end
  end

  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  resources :custom_fields
  resources :locations
  resources :project_targets
  resources :regions, defaults: {format: :json}
  resources :relationships, except: [:show]
  resources :roles
  resources :service_type_categories
  resources :service_types
  resources :services
  #resources :reports do
  #  resources :report_attachments
  #  member do
  #    patch :submit
  #  end
  #end
  resources :users
  resources :work_activities
  resources :hazardous_conditions
  resources :household_tasks

  devise_for :users, skip: [:sessions, :registrations, :confirmations, :passwords]

  as :user do
    get 'sign_in' => 'devise/sessions#new', as: :new_user_session
    post 'sign_in' => 'devise/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'sign_up' => 'registrations#new', as: :new_user_registration
    post 'sign_up' => 'registrations#create', as: :user_registration

    put 'sign_up' => 'devise/registrations#update', as: nil
    patch 'sign_up' => 'devise/registrations#update', as: nil

    get 'password/new' => 'devise/passwords#new', as: :new_user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    patch 'password' => 'devise/passwords#update', as: nil
    put 'password' => 'devise/passwords#update', as: nil

    get 'confirm_account' => 'devise/confirmations#show', as: :user_confirmation
  end

  # Api definition
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :comments, only: [:create]
      #resources :reports, only: [:update]
      resources :tokens, only: [:index]
      resources :households, only: [:index, :show, :create, :update]
      resources :income_sources, only: [:index, :show, :create, :update]
      resources :status_customization_work_activities, only: [:index, :show]
      resources :status_customization_hazardous_conditions, only: [:index, :show]
      resources :status_customization_household_tasks, only: [:index, :show]
      resources :relationships, only: [:index, :show]
      resources :people, only: [:index, :show, :create, :update]
      resources :follow_ups, only: [:index, :show, :create, :update]
      resources :service_type_categories, only: [:index]
      resources :service_types, only: [:index]
      resources :services, only: [:index]
      resources :service_instances, only: [:index, :show, :create, :update]
      resources :custom_fields, only: [:index]
      resources :custom_values, only: [:index, :create]
    end
  end

  authenticate :user, lambda {|u| u.has_role? 'Administrator'} do
    mount Sidekiq::Web => '/sidekiq'
  end

  post 'initialize'=> 'home#create'

  root to: "home#index"
end

app/models/target.rb
class Target < ActiveRecord::Base
	belongs_to :indicator
	belongs_to :reporting_period
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_indicator

  def index
    @targets = Target.where(indicator_id: params[:indicator_id]).all
  end

  def new
    @targets = Array.new

    ReportingPeriod.all.each do |reporting_period|
      new_target = Target.new do |t|
        t.reporting_period = reporting_period
        t.indicator = @indicator
      end

      @targets.push new_target
    end
    #@targets = [Target.new, Target.new, Target.new, Target.new, Target.new, Target.new, Target.new, Target.new, Target.new]
  end

  def edit_mulitple
  end

  def create_multiple

    target_values = params[:targets]

    target_values.each do |target_value|
      @indicator.targets.create(reporting_period_id: target_value[".reporting_period_id"].to_i, target_value: target_value[".target_value"].delete(",").to_i)
    end

    redirect_to indicators_path(@indicator), notice: t("action_messages.create_multiple", model: "Targets")

  end

  def update_multiple
    @target_values = params[:targets]

    @target_values.each do |target_value|
      target = Target.find_by(id: target_value[".id"])
      if target
        target.target_value = target_value[".target_value"]
        target.save
      end
    end

    redirect_to indicators_path(@indicator), notice: t("action_messages.update_multiple", model: "Targets")

  end

  private

  def set_indicator
    @indicator = Indicator.find(params[:indicator_id])
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/edit.html.erb
<div class="page-header">
  <%= link_to indicator_path(@indicator), class: 'btn btn-default' do %>
    <%= fa_icon "caret-left" %> Back to Indicator
  <% end %>
  <h1><%= t("targets.edit.title") %> - <%= @indicator.indicator %></h1>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">

      <div class="box-body">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Period 1</th>
              <th>Period 2</th>
              <th>Period 3</th>
              <th>Period 4</th>
              <th>Period 5</th>
              <th>Period 6</th>
              <th>Period 7</th>
              <th>Period 8</th>
              <th>Period 9</th>
              <th>Period 10</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right">
          <%= t "general.submit" %>
        </button>
        <%= link_to indicators_path,
          class: "btn btn-danger pull-right",
          style: "margin-right: 1rem" do %>
          <i class="fa fa-times"> </i> <%= t "general.cancel" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/targets/edit_multiple.html.erb
<div class="page-header">
  <%= link_to indicator_path(@indicator), class: 'btn btn-default' do %>
    <%= fa_icon "caret-left" %> Back to Indicator
  <% end %>
  <h1><%= t("targets.edit.title") %> - <%= @indicator.indicator %></h1>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_tag update_multiple_indicator_targets_path(@indicator), method: :put do %>
    <div class="box box-primary">

      <div class="box-body">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Reporting Period</th>
              <th>Target Value</th>
            </tr>
          </thead>
          <tbody>
              <% @indicator.targets.each do |target| %>
                <tr>
                  <td><%= target.reporting_period.name %></td>
                  <td>
                    <%= text_field_tag "targets[].target_value", target.target_value %>
                    <%= hidden_field_tag "targets[].id", target.id %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right">
          <%= t "general.submit" %>
        </button>
        <%= link_to indicators_path,
          class: "btn btn-danger pull-right",
          style: "margin-right: 1rem" do %>
          <i class="fa fa-times"> </i> <%= t "general.cancel" %>
        <% end %>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/targets/index.html.erb
<div class="page-header">
  <%= link_to indicator_path(@indicator), class: 'btn btn-default' do %>
    <%= fa_icon "caret-left" %> Back to Indicator
  <% end %>
  <h1><%= t("targets.edit.title") %> - <%= @indicator.indicator %></h1>
</div>

<div class="row">
  <div class="col-md-12">
    <form method="post" action="<%= indicator_targets_path(@indicator) %>">
    <div class="box box-primary">

      <div class="box-body">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Period 1</th>
              <th>Period 2</th>
              <th>Period 3</th>
              <th>Period 4</th>
              <th>Period 5</th>
              <th>Period 6</th>
              <th>Period 7</th>
              <th>Period 8</th>
              <th>Period 9</th>
              <th>Period 10</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
              <td><input type="text" id="period1Target" name="period1Target"/></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right">
          <%= t "general.submit" %>
        </button>
        <%= link_to indicators_path,
          class: "btn btn-danger pull-right",
          style: "margin-right: 1rem" do %>
          <i class="fa fa-times"> </i> <%= t "general.cancel" %>
        <% end %>
      </div>

    </div>
  </form>
  </div>
</div>

app/views/targets/new.html.erb
<div class="page-header">
  <%= link_to indicator_path(@indicator), class: 'btn btn-default' do %>
  <%= fa_icon "caret-left" %>
  Back to Indicator
  <% end %>
  <h1><%= t("targets.edit.title") %>
    -
    <%= @indicator.indicator %></h1>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_tag create_multiple_indicator_targets_path(@indicator) do %>
    <div class="box box-primary">

      <div class="box-body">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Reporting Period</th>
              <th>Target Value</th>
            </tr>
          </thead>
          <tbody>
            <% @targets.each do |target| %>
            <tr>
              <td><%= target.reporting_period.name %></td>
              <td>
                <%= text_field_tag "targets[].target_value", target.target_value %>
                <%= hidden_field_tag "targets[].reporting_period_id", target.reporting_period_id %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right">
          <%= t "general.submit" %>
        </button>
        <%= link_to indicators_path,
          class: "btn btn-danger pull-right",
          style: "margin-right: 1rem" do %>
        <i class="fa fa-times"></i>
        <%= t "general.cancel" %>
        <% end %>
      </div>

    </div>
    <% end %>
  </div>
</div>