config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :comments
  mount Ckeditor::Engine => '/ckeditor'

  get 'targets/index'

  get 'gender_count/:id' => 'projects#gender_count'

  get '*path', to: 'home#setup',
    constraints: ProjectConstraints.new

  resource :project do
    get :dashboard
    get :status_config
    get :reporting_table
  end

  resources :households do
    resources :income_sources
    resources :people do
      resources :follow_ups
      resources :service_instances
      resources :timelines, only: [:index]
    end
    post :finalize, on: :member
  end

  resources :indicators do
    resources :indicator_details
    resources :targets do
      collection do
        get :edit_multiple
        post :create_multiple
        put :update_multiple
      end
    end
  end

  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  resources :custom_fields
  resources :locations
  resources :project_targets
  resources :regions, defaults: {format: :json}
  resources :relationships, except: [:show]
  resources :roles
  resources :service_type_categories
  resources :service_types
  resources :services
  #resources :reports do
  #  resources :report_attachments
  #  member do
  #    patch :submit
  #  end
  #end
  resources :users
  resources :work_activities
  resources :hazardous_conditions
  resources :household_tasks

  devise_for :users, skip: [:sessions, :registrations, :confirmations, :passwords]

  as :user do
    get 'sign_in' => 'devise/sessions#new', as: :new_user_session
    post 'sign_in' => 'devise/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'sign_up' => 'registrations#new', as: :new_user_registration
    post 'sign_up' => 'registrations#create', as: :user_registration

    put 'sign_up' => 'devise/registrations#update', as: nil
    patch 'sign_up' => 'devise/registrations#update', as: nil

    get 'password/new' => 'devise/passwords#new', as: :new_user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    patch 'password' => 'devise/passwords#update', as: nil
    put 'password' => 'devise/passwords#update', as: nil

    get 'confirm_account' => 'devise/confirmations#show', as: :user_confirmation
  end

  # Api definition
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :comments, only: [:create]
      #resources :reports, only: [:update]
      resources :tokens, only: [:index]
      resources :households, only: [:index, :show, :create, :update]
      resources :income_sources, only: [:index, :show, :create, :update]
      resources :status_customization_work_activities, only: [:index, :show]
      resources :status_customization_hazardous_conditions, only: [:index, :show]
      resources :status_customization_household_tasks, only: [:index, :show]
      resources :relationships, only: [:index, :show]
      resources :people, only: [:index, :show, :create, :update]
      resources :follow_ups, only: [:index, :show, :create, :update]
      resources :service_type_categories, only: [:index]
      resources :service_types, only: [:index]
      resources :services, only: [:index]
      resources :service_instances, only: [:index, :show, :create, :update]
      resources :custom_fields, only: [:index]
      resources :custom_values, only: [:index, :create]
    end
  end

  authenticate :user, lambda {|u| u.has_role? 'Administrator'} do
    mount Sidekiq::Web => '/sidekiq'
  end

  post 'initialize'=> 'home#create'

  root to: "home#index"
end

app/models/translation.rb
class Translation < ActiveRecord::Base
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_filter :find_locale
  before_filter :retrieve_key, only: [:create, :update]
  before_filter :find_translation, only: [:edit, :update]

  def index
    @translations = Translation.locale(@locale)
  end

  def new
    @translation = Translation.new(locale: @locale, key: params[:key])
  end

  def create
    @translation = Translation.new(translation_params)
    if @translation.save
      flash[:success] = "Translation for #{@key} updated."
      I18n.backend.reload!
      redirect_to locale_translations_url(@locale)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @translation.update(translation_params)
      flash[:notice] = "Translation for #{@key} updated."
      I18n.backend.reload!
      redirect_to locale_translations_url(@locale)
    else
      render :edit
    end
  end

  def destroy
    Translation.destroy(params[:id])
    I18n.backend.reload!
    redirect_to locale_translations_url(@locale)
  end

  private

  def find_locale
    @locale = params[:locale_id]
  end

  def find_translation
    @translation = Translation.find(params[:id])
  end

  def retrieve_key
    @key = params[:i18n_backend_active_record_translation][:key]
  end

  def translation_params
    params.require(:i18n_backend_active_record_translation).permit(:locale, :key, :value)
  end

  def default_translation_value
    I18n.t(@translation.key, locale: @locale)
  end

end

app/helpers/translations_helper.rb
module TranslationsHelper
  def translation_keys(i18n_locale)
    case i18n_locale
    when 'en'
      en_keys
    when 'jp'
      jp_keys
    else
      default_keys
    end
  end

  def translation_for_key(translations, key)
    hits = translations.to_a.select { |t| t.key == key }
    hits.first
  end

  private

  def en_keys
    %w(welcome site_description contact_name)
  end

  def jp_keys
    %w(welcome site_description)
  end

  def default_keys
    %w(welcome site_description)
  end
end

app/views/translations/_form.html.erb
<%= form_for @translation, url: locale_translation_path, html: { role: "form" } do |f| %>
<%= error_messages(@translation) %>

<div class="box-body">

    <div class="form-group">
      <%= f.label :locale %>
      <%= f.text_field :locale, readonly: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :key %>
      <%= f.text_field :key, readonly: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :value %>
      <%= f.text_area :value, :value => f.object.value, class: "form-control" %>
    </div>

</div>

<div class="box-footer">
  <button type="submit" class="btn btn-primary pull-right">
    <%= t "general.submit" %>
  </button>
  <%= link_to locale_translations_url(@locale),
    class: "btn btn-danger pull-right",
    style: "margin-right: 1rem" do %>
    <i class="fa fa-times"> </i> <%= t "general.cancel" %>
  <% end %>
</div>

<% end %>

app/views/translations/edit.html.erb
<div class="row">
  <div class="col-md-10 col-xs-12">

    <div class="box box-primary">
      <div class="box-header with-border">
        <%= fa_icon "language" %>
        <h3 class="box-title">
          <%= t "translations.edit.form_title" %>
        </h3>
      </div>

      <%= render 'form' %>

    </div>

  </div>
</div>

app/views/translations/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <%= fa_icon "language" %>
        <h1 class="box-title"><%= t("translations.index.title") %>
          for
          <%= @locale %></h1>
        <div class="box-tools">
          <%= link_to new_locale_translation_url(@locale), class: "btn btn-primary" do %>
          <%= fa_icon "plus" %>
          <%= t("translation.index.add") %>
          <% end %>
        </div>
      </div>

      <div class="box-body">
        <br/>
        <table class="table table-bordered table-striped" id="translationsTable">
          <thead>
            <tr>
              <th>Translation Key</th>
              <th>Translation Value</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @translations.each do |translation| %>
              <tr id="<%= translation.key %>">
                <td><%= translation.key %></td>
                <td><%= translation.value %></td>
                <td>
                  <%= link_to t("general.edit"), edit_locale_translation_url(@locale, translation) %>
                  <%= link_to t("general.delete"), locale_translation_url(@locale, translation), method: :delete, data: { confirm: t("general.confirm") } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/translations/new.html.erb
<div class="row">
  <div class="col-md-10 col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <%= fa_icon "language" %>
        <h3 class="box-title">
          <%= t "translations.new.form_title" %>
        </h3>
      </div>

      <%= form_for @translation, url: locale_translations_path do |f| %>
      <%= error_messages(@translation) %>

      <div class="box-body">

        <div class="form-group">
          <%= f.label :locale %>
          <%= f.text_field :locale, readonly: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :key %>
          <%= f.text_field :key, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :value %>
          <%= f.text_area :value, :value => f.object.value, class: "form-control" %>
        </div>

      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right">
          <%= t "general.submit" %>
        </button>
        <%= link_to locale_translations_url(@locale),
            class: "btn btn-danger pull-right",
            style: "margin-right: 1rem" do %>
        <i class="fa fa-times"></i>
        <%= t "general.cancel" %>
        <% end %>
      </div>

      <% end %>

    </div>
  </div>
</div>