config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :comments
  mount Ckeditor::Engine => '/ckeditor'

  get 'targets/index'

  get 'gender_count/:id' => 'projects#gender_count'

  get '*path', to: 'home#setup',
    constraints: ProjectConstraints.new

  resource :project do
    get :dashboard
    get :status_config
    get :reporting_table
  end

  resources :households do
    resources :income_sources
    resources :people do
      resources :follow_ups
      resources :service_instances
      resources :timelines, only: [:index]
    end
    post :finalize, on: :member
  end

  resources :indicators do
    resources :indicator_details
    resources :targets do
      collection do
        get :edit_multiple
        post :create_multiple
        put :update_multiple
      end
    end
  end

  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  resources :custom_fields
  resources :locations
  resources :project_targets
  resources :regions, defaults: {format: :json}
  resources :relationships, except: [:show]
  resources :roles
  resources :service_type_categories
  resources :service_types
  resources :services
  #resources :reports do
  #  resources :report_attachments
  #  member do
  #    patch :submit
  #  end
  #end
  resources :users
  resources :work_activities
  resources :hazardous_conditions
  resources :household_tasks

  devise_for :users, skip: [:sessions, :registrations, :confirmations, :passwords]

  as :user do
    get 'sign_in' => 'devise/sessions#new', as: :new_user_session
    post 'sign_in' => 'devise/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'sign_up' => 'registrations#new', as: :new_user_registration
    post 'sign_up' => 'registrations#create', as: :user_registration

    put 'sign_up' => 'devise/registrations#update', as: nil
    patch 'sign_up' => 'devise/registrations#update', as: nil

    get 'password/new' => 'devise/passwords#new', as: :new_user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    patch 'password' => 'devise/passwords#update', as: nil
    put 'password' => 'devise/passwords#update', as: nil

    get 'confirm_account' => 'devise/confirmations#show', as: :user_confirmation
  end

  # Api definition
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :comments, only: [:create]
      #resources :reports, only: [:update]
      resources :tokens, only: [:index]
      resources :households, only: [:index, :show, :create, :update]
      resources :income_sources, only: [:index, :show, :create, :update]
      resources :status_customization_work_activities, only: [:index, :show]
      resources :status_customization_hazardous_conditions, only: [:index, :show]
      resources :status_customization_household_tasks, only: [:index, :show]
      resources :relationships, only: [:index, :show]
      resources :people, only: [:index, :show, :create, :update]
      resources :follow_ups, only: [:index, :show, :create, :update]
      resources :service_type_categories, only: [:index]
      resources :service_types, only: [:index]
      resources :services, only: [:index]
      resources :service_instances, only: [:index, :show, :create, :update]
      resources :custom_fields, only: [:index]
      resources :custom_values, only: [:index, :create]
    end
  end

  authenticate :user, lambda {|u| u.has_role? 'Administrator'} do
    mount Sidekiq::Web => '/sidekiq'
  end

  post 'initialize'=> 'home#create'

  root to: "home#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_targets, :dependent => :destroy
  has_many :locations, :dependent => :destroy
  belongs_to :region

  validates_presence_of :title, :name, :region_id

  accepts_nested_attributes_for :project_targets, :locations

  after_create :generate_common_indicators

  def generate_common_indicators
    Indicator.create_common_indicators()
  end

  def headquarters_address
    address = self.headquarters_location

    unless address.nil?
      return "#{self.organization}\n#{address.to_mailing}"
    end

    return nil
  end

  def headquarters_location
    self.locations.where('location_type_id = 1').first
  end

  def field_address
    address = self.field_location

    address&.to_mailing || nil
  end

  def field_addresses
    "TODO"
  end

  def field_location
    self.locations.where('location_type_id = 2').first
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.first
  end

  def dashboard
    @project = Project.first
    @total_children = Child.count
    @total_households = Household.count
    @total_services = Service.count

    @total_children_target = 0
    @total_children_percentage = 0
    @total_households_target = 0
    @total_households_percentage = 0

    total_children_target =
      @project.project_targets.find_by(project_target_type_id: 2)

    if total_children_target
      @total_children_target = total_children_target.target.to_i
      @total_children_percentage =
        (@total_children.to_f / @total_children_target.to_f) * 100.0
    end

    total_households_target =
      @project.project_targets.find_by(project_target_type_id: 3)

    if total_households_target
      @total_households_target = total_households_target.target.to_i
      @total_households_percentage =
        (@total_households.to_f / @total_households_target.to_f) * 100.0
    end

    @project_complete_percentage = (Date.today.mjd - @project.start_date.mjd) /
      (@project.end_date.mjd - @project.start_date.mjd).to_f * 100.0

    @new_children = Child.order('created_at desc').limit(8)

    reporting_periods = ReportingPeriod.order(:start_date).map(&:name)
    colors = [
      "#3d4341", "#75b5c4", "#c9cb9d", "#c88c85", "#73342e",
      "#bf94c8", "#5a763b", "#4f2962", "#5f73c2", "#6fd291",
      "#cda13e", "#cc488f", "#d25039", "#99d547", "#9047cb"
    ]

    @children_target_vs_actual = {
      labels: reporting_periods,
      datasets: [
        {
          label: "Actuals",
          data: Array.new(8) { rand 0..9 },
          backgroundColor: colors[0]
        },
        {
          label: "Targets",
          data: Array.new(8) { rand 1..8 },
          backgroundColor: colors[1]
        }
      ]
    }

    @households_target_vs_actual = {
      labels: reporting_periods,
      datasets: [
        {
          label: "Actuals",
          data: Array.new(8) { rand 0..9 },
          backgroundColor: colors[0]
        },
        {
          label: "Targets",
          data: Array.new(8) { rand 1..8 },
          backgroundColor: colors[1]
        }
      ]
    }

    @children_by_age = {
      labels: ["5-8", "9-11", "12-14", "15-17"],
      datasets: [{
        data: Child.group_by_age[1..-1],
        backgroundColor: colors[7..-1]
      }]
    }

    sex_count = Child.group(:sex).count

    @children_by_gender = {
      labels: Child.gender_names,
      datasets: [{
        data: [sex_count[1], sex_count[2]],
        backgroundColor: [colors[8], colors[12]]
      }]
    }

    @bar_chart_options = {
      width: 400,
      height: 200,
      scales: {
        yAxes: [{
          ticks: { min: 0, max: 10 }
        }]
      }
    }

    @pie_chart_options = {
      width: '330', height: '230',
      maintainAspectRatio: false,
      legend: { position: 'right' }
    }

    render 'dashboard'
  end

  def status_config
  end

  def reporting_table
    @project = Project.first
    @reporting_periods = ReportingPeriod.all
    @indicators = Indicator.all

  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def progress_bar value
    return '' if value.nil? || value == ''
    content_tag :div, class: 'progress' do
      content_tag :div,'',
        { class: 'progress-bar', style: "width:#{number_to_percentage value}" }
    end
  end

  def info_box title, value, percent, description, icon, color
    content_tag :div, class: "info-box bg-#{color}" do
      content_tag(:span, fa_icon(icon), {class: "info-box-icon"}) +
      content_tag(:div, class: "info-box-content") do
        concat content_tag(:span, title, class: "info-box-text")
        concat content_tag(:span, value, class: "info-box-number")
        concat progress_bar(percent)
        concat content_tag(:span, description, class: "progress-description")
      end
    end 
  end

  def collapsible_box title, color, &block
    content_tag :div, class: "box box-#{color}" do
      concat collapsible_box_header title
      concat box_body(&block)
    end
  end

  def collapsible_box_header title, &block
    content_tag :div, class: "box-header with-border" do
      concat content_tag(:h3, title, class: "box-title")
      concat box_tools &block
    end
  end

  def box_body &block
    content_tag :div, class: "box-body" do
      capture(&block)
    end
  end

  def box_tools &block
    content_tag :div, class: "box-tools pull-right" do
      if block_given?
        concat(content_tag(:span, class: "box-tools") do
          capture(&block)
        end)
      end
      concat(content_tag(:button, {class: "btn btn-box-tool",
        data: {widget: "collapse"}}) do
        fa_icon "minus"
      end)
      concat(content_tag(:button, {class: "btn btn-box-tool",
        data: {widget: "remove"}}) do
        fa_icon "times"
      end)
    end
  end
end

app/views/projects/_hazardous_condition.html.erb
<tr>
  <td><%= hazardous_condition.code %></td>
  <td><%= link_to hazardous_condition.display_name, edit_hazardous_condition_path(hazardous_condition), remote: true %></td>
  <td>
    <%= link_to hazardous_condition_path(hazardous_condition), method: :delete, data: {confirm: 'Are you sure?'} do %>
      <%= fa_icon "trash" %>
      <%= t "general.delete" %>
    <% end %>
  </td>
</tr>

app/views/projects/_household_task.html.erb
<tr>
  <td><%= household_task.code %></td>
  <td><%= link_to household_task.display_name, edit_household_task_path(household_task), remote: true %></td>
  <td>
    <%= link_to household_task_path(household_task), method: :delete, data: {confirm: 'Are you sure?'} do %>
      <%= fa_icon "trash" %>
      <%= t "general.delete" %>
    <% end %>
  </td>
</tr>

app/views/projects/_location_fields.html.erb
<tr>
  <td>
    <%= f.collection_select :location_type_id, LocationType.all, :id, :name,
             { include_blank: true, prompt: true }, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :name, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :address_line1, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :address_line2, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :city, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :state, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :zip, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :country, class: "form-control" %>
  </td>
  <td class="options-controls">
    <button type="submit" class="btn btn-primary options-control"><%= fa_icon :plus %></button>
    <a href="#" data-hide="location-fields" class="options-control">
      <%= fa_icon :times, class: 'text-danger' %>
    </a>
  </td>
<tr>

app/views/projects/_location_show.html.erb
<tr>
  <td>
    <%= content_tag :span, data: { type: "select", resource: "location",
      name: "location_type_id", source: LocationType.for_select.to_json,
      url: location_path(location), value: location.location_type_id } do %>
      <%= location.location_type.name %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "name", url: location_path(location) } do %>
      <%= location.name %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "address_line1", url: location_path(location) } do %>
      <%= location.address_line1 %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "address_line2", url: location_path(location) } do %>
      <%= location.address_line2 %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "city", url: location_path(location) } do %>
      <%= location.city %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "state", url: location_path(location) } do %>
      <%= location.state %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "zip", url: location_path(location) } do %>
      <%= location.zip %>
    <% end %>
  </td>
  <td>
    <%= content_tag :span, data: { type: "text", resource: "location",
      name: "country", url: location_path(location) } do %>
      <%= location.country %>
    <% end %>
  </td>
  <td class="options-controls">
    <%= link_to location_path(location), method: :delete,
      class: 'options-control', data: { confirm: t("general.confirm") } do %>
      <%= fa_icon 'times', class: 'text-danger' %>
    <% end %>
  </td>
</tr>

app/views/projects/_project_region_fields.html.erb
<fieldset class="associated-fields">
  <div class="form-group">
    <%= f.label :country %>
    <%= f.country_select :country, {include_blank: true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>

  <%= f.hidden_field :_destroy %>

  <%= link_to '#', class: "remove_fields pull-right" do %>
    <i class="fa fa-trash-o"></i><%= t("general.delete") %>
  <% end %>
</fieldset>

app/views/projects/_project_target_show.html.erb
<tr>
  <td><%= project_target.project_target_type.name %></td>
  <td>
    <%= number_with_precision(project_target.target, precision: 0, delimiter: ',') %>
  </td>
</tr>

app/views/projects/_work_activity.html.erb
<tr>
  <td><%= work_activity.code %></td>
  <td><%= link_to work_activity.display_name, edit_work_activity_path(work_activity), remote: true %></td>
  <td>
    <%= link_to work_activity_path(work_activity), method: :delete, data: {confirm: 'Are you sure?'} do %>
      <%= fa_icon "trash" %>
      <%= t "general.delete" %>
    <% end %>
  </td>
</tr>

app/views/projects/dashboard.html.erb
<% provide(:title, @project.name + " Dashboard") %>

<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12">
    <%= info_box("Participants",
        number_with_delimiter(@total_children),
        @total_children_percentage,
        "#{number_to_percentage(@total_children_percentage, precision: 0)} " +
        "of #{number_with_delimiter(@total_children_target)} targeted " +
        "participants serviced", "child", "aqua") %>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <%= info_box("Households",
        number_with_delimiter(@total_households),
        @total_households_percentage,
      "#{number_to_percentage(@total_households_percentage, precision: 0)} " +
        "of #{number_with_delimiter(@total_households_target)} targeted " +
        "households serviced", "home", "green") %>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <%= info_box "Services", number_with_delimiter(@total_services), "", "",
        "cutlery", "red" %>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box bg-yellow clickable" id="timeline">
      <span class="info-box-icon"><%= fa_icon "calendar" %></span>
      <div class="info-box-content">
        <span class="info-box-text">Timeline</span>
        <span class="info-box-number">
          <%= Date.today.strftime('%A, %B %d, %Y') %>
        </span>
        <%= progress_bar @project_complete_percentage %>
        <span class="progress-description" id="time-elapsed">
          <%= distance_of_time_in_words @project.start_date, Date.today %>
          into your project
        </span>
        <span class="progress-description hidden" id="time-remaining">
          <%= distance_of_time_in_words Date.today, @project.end_date %>
          remain in your project
        </span>
      </div>
    </div>
  </div>
</div>

<% # note the deep_dup for @chart_options. chartjs_ror deletes options from
   # the passed in object. This works around that. Might not be ideal. %>
<div class="row">
  <div class="col-md-6">
    <%= collapsible_box(
        raw("Participants Target vs Actual by Reporting Period " +
        "<small>(#{@project.start_date} – #{@project.end_date})</small>"),
        "primary") do %>
      <%= bar_chart @children_target_vs_actual, @bar_chart_options.deep_dup %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= collapsible_box(
        raw("Households Target vs Actual by Reporting Period " +
        "<small>(#{@project.start_date} – #{@project.end_date})</small>"),
        "primary") do %>
      <%= bar_chart @households_target_vs_actual, @bar_chart_options %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <%= collapsible_box("Participants by Age", "primary") do %>
      <%= doughnut_chart @children_by_age, @pie_chart_options.deep_dup %>
    <% end %>
  </div>

  <div class="col-md-4">
    <%= collapsible_box("Participants by Gender", "primary") do %>
      <%= pie_chart @children_by_gender, @pie_chart_options %>
    <% end %>
  </div>

  <div class="col-md-4">
    <div class="box box-danger">
      <%= collapsible_box_header "Newest Participants" do %>
        <span class="label label-danger">
          <%= @new_children.count %> New Members
        </span>
      <% end %>

      <div class="box-body no-padding">
        <ul class="users-list clearfix">
          <% @new_children.each do |child| %>
            <li>
              <%= preview_avatar child, {size: "small"} %>
              <%= link_to child.full_name, household_person_path(child.household, child), {class: "users-list-name"} %>
              <span class="users-list-date">
                <%= child.created_at.strftime("%Y-%m-%d") %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/projects/reporting_table.html.erb
<div class="page-header">
  <h1><%= @project.name %> Reporting Table</h1>
</div>

<div class="box box-primary">

  <div class="box-body">
    <table id="reporting-table"
      class="table table-bordered table-condensed table-striped">
      <thead>
        <tr>
          <th>Project Outcomes/Indicators</th>
          <th>Intake Value</th>
          <th>Target/Actual</th>
          <th>Baseline</th>
          <% @reporting_periods.each do | rp | %>
          <th><%= rp.name %></th>
          <% end %>
          <th>Final Value</th>
          <th>Frequency of Report</th>
          <th>Life of Project Target</th>
          <th>Life of Project Achieved</th>
          <th>Comment</th>
        </tr>
      </thead>
      <tbody>
        <% @indicators.order(:code).each do | i | %>
          <tr>
            <td><%= i.name %></td>
            <td>&nbsp;</td>
            <td>Target<br/>Actual</td>
            <td><%= i.baseline %></td>
            <% @reporting_periods.each do | rp | %>
              <% details = i.indicator_details.where("reporting_period_id = ?", rp.id).first %>
              <td>
                <%= details.target unless details.nil? %><br/>
                <%= details.actual unless details.nil? %>
              </td>
            <% end %>
            <td>&nbsp;</td>
            <td><%= i.reporting_frequency.name %></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/show.html.erb
<% title @project.title %>
<% description @project.cooperative_agreement_number %>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "fort-awesome" %>
    <h3 class="box-title"><%= t("projects.show.details") %></h3>
  </div>
  <div class="box-body">
    <table class="table table-hover table-listing table-condensed">
      <tbody>
        <tr>
          <th><%= Project.human_attribute_name(:name) %></th>
          <td><%= @project.name %></td>
        </tr>
        <tr>
          <th><%= Project.human_attribute_name(:title) %></th>
          <td><%= @project.title %></td>
        </tr>
        <tr>
          <th>
            <%= Project.human_attribute_name(:cooperative_agreement_number) %>
          </th>
          <td><%= @project.cooperative_agreement_number %></td>
        </tr>
        <tr>
          <th><%= Project.human_attribute_name(:start_date) %></th>
          <td><%= @project.start_date %></td>
        </tr>
        <tr>
          <th><%= Project.human_attribute_name(:end_date) %></th>
          <td><%= @project.end_date %></td>
        </tr>
        <tr>
          <th><%= Project.human_attribute_name(:organization) %></th>
          <td><%= @project.organization %></td>
        </tr>
        <tr>
          <th><%= Project.human_attribute_name(:funding_amount) %></th>
          <td>
            <%= number_with_precision(@project.funding_amount,
              precision: 0, delimiter: ',') %>
          </td>
        </tr>
        <tr>
          <th><%= Project.human_attribute_name(:region) %></th>
          <td><%= @project.region.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "map-marker" %>
    <h3 class="box-title"><%= t("projects.show.locations") %></h3>
    <div class="box-tools pull-right">
      <%= link_to '#', 'data-show': 'location-fields',
        class: 'btn btn-primary btn-sm' do %>
        <%= fa_icon "plus", text: t("general.add") %>
      <% end %>
    </div>
  </div>
  <div class="box-body">
    <div class="tabled-responsive">
      <%= form_for(Location.new, remote: :true, html: {role: "form"}) do |f| %>
      <%= f.hidden_field :project_id, value: @project.id %>
        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th><%= Location.human_attribute_name(:location_type_id) %></th>
              <th><%= Location.human_attribute_name(:name) %></th>
              <th><%= Location.human_attribute_name(:address_line1) %></th>
              <th><%= Location.human_attribute_name(:address_line2) %></th>
              <th><%= Location.human_attribute_name(:city) %></th>
              <th><%= Location.human_attribute_name(:state) %></th>
              <th><%= Location.human_attribute_name(:zip) %></th>
              <th><%= Location.human_attribute_name(:country) %></th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody id="locations">
            <%= render partial: "location_show",
              collection: @project.locations, as: 'location' %>
          </tbody>
          <tbody id="location-fields" style="display: none">
            <%= render partial: 'location_fields', locals: {f: f} %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>
<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "bullseye" %>
    <h3 class="box-title"><%= t("projects.show.targets") %></h3>
  </div>
  <div class="box-body">
    <div class="table-responsive">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th><%=
              ProjectTarget.human_attribute_name(:project_target_type_id)
            %></th>
            <th>
              <%= ProjectTarget.human_attribute_name(:target_value) %>
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "project_target_show",
            collection: @project.project_targets, as: 'project_target' %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/projects/show.js.erb
$('.content-header').html(
    '<div class="alert alert-success alert-dismissable">' +
    '  <i class="fa fa-check"></i>' +
    '  <button type="button" class="close" data-dismiss="alert" ' +
    '    aria-hidden="true">×</button><b><%= j notice %></b>' +
    '</div>').fadeIn().delay(3000).fadeOut();

$('#locations').html(
  '<%= j render(partial: "location_show", collection: @project.locations,
    as: "location") %>'
);

$('#locations td span').editable({
  mode: 'inline'
});

$('#new_location')[0].reset();
$('#location-fields').hide();

app/views/projects/status_config.html.erb
<div class="page-header">
  <h1><%= t("projects.status_config.title") %></h1>
  <p>Use this page to customize the parameters of the work and education automatic calculation</p>
</div>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "truck" %>
    <h3 class="box-title">
      <%= t("projects.status_config.work_activities_title") %>
    </h3>
  </div>
  <div class="box-body">
    <div class="table-responsive">
      <table id="work-activities-data-table" class="table table-condensed table-striped">
        <thead>
          <tr>
            <th><%= WorkActivity.human_attribute_name(:code) %></th>
            <th><%= WorkActivity.human_attribute_name(:display_name) %></th>
            <th><%= t "general.delete" %></th>
          </tr>
        </thead>

        <tbody id="work_activities_details">
          <%= render partial: "work_activity",
          collection: WorkActivity.all.order(:id) %>
        </tbody>
      </table>
    </div>

  </div>
  <!-- box-body -->
  <div class="box-footer clearfix">
    <%= link_to t("work_activities.new.add"),
          new_work_activity_path(@work_activity), remote: true,
          class: "btn btn-primary" %>
  </div>
  <!-- box-footer -->
</div>
<!-- box -->

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "exclamation-triangle" %>
    <h3 class="box-title">
      <%= t("projects.status_config.hazardous_conditions_title") %>
    </h3>
  </div>
  <div class="box-body">
    <div class="table-responsive">
      <table id="hazardous_conditions-data-table" class="table table-condensed table-striped">
        <thead>
          <tr>
            <th><%= HazardousCondition.human_attribute_name(:code) %></th>
            <th><%= HazardousCondition.human_attribute_name(:display_name) %></th>
            <th><%= t "general.delete" %></th>
          </tr>
        </thead>

        <tbody id="hazardous_conditions_details">
          <%= render partial: "hazardous_condition",
          collection: HazardousCondition.all.order(:id) %>
        </tbody>
      </table>
    </div>
  </div>
  <!-- box-body -->
  <div class="box-footer clearfix">
    <%= link_to t("hazardous_conditions.new.add"), new_hazardous_condition_path(@hazardous_condition),
          remote: true, class: "btn btn-primary" %>
  </div>
  <!-- box-footer -->
</div>
<!-- box -->

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "tasks" %>
    <h3 class="box-title">
      <%= t("projects.status_config.household_tasks_title") %>
    </h3>
  </div>
  <div class="box-body">
    <div class="table-responsive">
      <table id="household_tasks-data-table" class="table table-condensed table-striped">
        <thead>
          <tr>
            <th><%= HouseholdTask.human_attribute_name(:code) %></th>
            <th><%= HouseholdTask.human_attribute_name(:display_name) %></th>
            <th><%= t "general.delete" %></th>
          </tr>
        </thead>
        <tbody id="household_tasks_details">
          <%= render partial: "household_task",
          collection: HouseholdTask.all.order(:id) %>
        </tbody>
      </table>
    </div>
  </div>
  <!-- box-body -->
  <div class="box-footer clearfix">
    <%= link_to t("household_tasks.new.add"), new_household_task_path(@household_task),
          remote: true, class: "btn btn-primary" %>
  </div>
  <!-- box-footer -->
</div>
<!-- box -->

<div class="modal modal-info fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="detailModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

app/views/projects/status_config.js.erb
$("#detailModal").modal("hide");

$(".content-header").html(
    '<div class="alert alert-success alert-dismissable">' +
    '  <i class="fa fa-check"></i>' +
    '  <button type="button" class="close" data-dismiss="alert" ' +
    '    aria-hidden="true">×</button><b><%= j notice %></b>' +
    '</div>').fadeIn().delay(3000).fadeOut();

$("#work_activities_details").html(
  '<%= j render partial: "work_activity",
    collection: WorkActivity.all.order(:id) %>'
);

$("#hazardous_conditions_details").html(
  '<%= j render partial: "hazardous_condition",
    collection: HazardousCondition.all.order(:id) %>'
);

$("#household_tasks_details").html(
  '<%= j render partial: "household_task",
    collection: HouseholdTask.all.order(:id) %>'
);