config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :comments
  mount Ckeditor::Engine => '/ckeditor'

  get 'targets/index'

  get 'gender_count/:id' => 'projects#gender_count'

  get '*path', to: 'home#setup',
    constraints: ProjectConstraints.new

  resource :project do
    get :dashboard
    get :status_config
    get :reporting_table
  end

  resources :households do
    resources :income_sources
    resources :people do
      resources :follow_ups
      resources :service_instances
      resources :timelines, only: [:index]
    end
    post :finalize, on: :member
  end

  resources :indicators do
    resources :indicator_details
    resources :targets do
      collection do
        get :edit_multiple
        post :create_multiple
        put :update_multiple
      end
    end
  end

  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  resources :custom_fields
  resources :locations
  resources :project_targets
  resources :regions, defaults: {format: :json}
  resources :relationships, except: [:show]
  resources :roles
  resources :service_type_categories
  resources :service_types
  resources :services
  #resources :reports do
  #  resources :report_attachments
  #  member do
  #    patch :submit
  #  end
  #end
  resources :users
  resources :work_activities
  resources :hazardous_conditions
  resources :household_tasks

  devise_for :users, skip: [:sessions, :registrations, :confirmations, :passwords]

  as :user do
    get 'sign_in' => 'devise/sessions#new', as: :new_user_session
    post 'sign_in' => 'devise/sessions#create', as: :user_session
    delete 'sign_out' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'sign_up' => 'registrations#new', as: :new_user_registration
    post 'sign_up' => 'registrations#create', as: :user_registration

    put 'sign_up' => 'devise/registrations#update', as: nil
    patch 'sign_up' => 'devise/registrations#update', as: nil

    get 'password/new' => 'devise/passwords#new', as: :new_user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    patch 'password' => 'devise/passwords#update', as: nil
    put 'password' => 'devise/passwords#update', as: nil

    get 'confirm_account' => 'devise/confirmations#show', as: :user_confirmation
  end

  # Api definition
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :comments, only: [:create]
      #resources :reports, only: [:update]
      resources :tokens, only: [:index]
      resources :households, only: [:index, :show, :create, :update]
      resources :income_sources, only: [:index, :show, :create, :update]
      resources :status_customization_work_activities, only: [:index, :show]
      resources :status_customization_hazardous_conditions, only: [:index, :show]
      resources :status_customization_household_tasks, only: [:index, :show]
      resources :relationships, only: [:index, :show]
      resources :people, only: [:index, :show, :create, :update]
      resources :follow_ups, only: [:index, :show, :create, :update]
      resources :service_type_categories, only: [:index]
      resources :service_types, only: [:index]
      resources :services, only: [:index]
      resources :service_instances, only: [:index, :show, :create, :update]
      resources :custom_fields, only: [:index]
      resources :custom_values, only: [:index, :create]
    end
  end

  authenticate :user, lambda {|u| u.has_role? 'Administrator'} do
    mount Sidekiq::Web => '/sidekiq'
  end

  post 'initialize'=> 'home#create'

  root to: "home#index"
end

app/models/household.rb
class Household < ActiveRecord::Base
  validates :name, presence: true

  has_many :people
  has_many :income_sources

  accepts_nested_attributes_for :people, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :income_sources, allow_destroy: true, reject_if: :all_blank

  def children
    self.people.who_are_children
  end

  def adults
    self.people.who_are_adults
  end

  def custom_sections
    CustomSection.where(model_type: 'Household')
  end
end

app/controllers/api/v1/households_controller.rb
class Api::V1::HouseholdsController < Api::ApiController
  before_filter :ensure_user_allowed

  # GET /api/households
  def index
    render json: Household.all.to_json
  end

  # GET /api/households/1
  def show
    if Household.exists?(params[:id])
      set_household
      render json: @household.to_json
    else
      render status: 404, json: '{"status":"failure"}'
    end
  end

  # POST /api/households
  def create
    @household = Household.new(household_params)
    if @household.save
      render status: 201, json: '{"status":"success","updated_at":"' +
        get_datetime_formatted(@household.updated_at) + '","created_at":"' +
        get_datetime_formatted(@household.created_at) + '","id":"' +
        @household.id.to_s + '"}'
    else
      render status: 500, json: '{"status":"failure"}'
    end
  end

  # PUT /api/households/1
  def update
    if Household.exists?(params[:id])
      set_household
      if @household.update(household_params)
        render json: '{"status":"success", "updated_at":"' +
          get_datetime_formatted(@household.updated_at) + '"}'
      else
        render status: 500, json: '{"status":"failure"}'
      end
    else
      render status: 404, json: '{"status":"failure"}'
    end
  end

  private

  def set_household
    @household = Household.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def household_params
    params.require(:household).permit(
      :name, :code, :intake_date, :address_line_1, :address_line_2,
      :postal_code, :dependent_locality, :locality, :adminv_area,
      :dependent_adminv_area, :country, :address_info, :latitude, :longitude,
      :position_accuracy, :altitude, :altitude_accuracy, :heading, :speed,
      :gps_recorded_at)
  end

end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  before_action :set_project
  before_action :set_household, only: [:show, :edit, :update, :destroy]
  before_action :set_regions, only: [:new, :show, :edit, :update]

  # GET /households
  def index
    @households = Household.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="' + t('people.export.names.full_intake_list_filename') + '"'
      }
    end
  end

  # GET /households/1
  def show
    @children = @household.children
    @adults = @household.adults
    @people = @household.people
    if ! CustomSection.where(model_type: 'Household', sort_order: 1).empty?
      @section_1_custom_fields = CustomSection.where(model_type: 'Household', sort_order: 1).first.custom_fields
    else
      @section_1_custom_fields = Array.new
    end
    @sections = CustomSection.where('model_type = ? AND sort_order > ?', 'Household', 1)
  end

  # GET /households/new
  def new
    @household = Household.new
    @section_1_custom_fields = CustomSection.where(model_type: 'Household', sort_order: 1).first.custom_fields unless CustomSection.where(model_type: 'Household', sort_order: 1).empty?
    @sections = CustomSection.where('model_type = ? AND sort_order > ?', 'Household', 1)
    @person_custom_fields = CustomField.where(model_type: 'Person')
  end

  # GET /households/1/edit
  def edit
    @section_1_custom_fields = CustomSection.where(model_type: 'Household', sort_order: 1).first.custom_fields unless CustomSection.where(model_type: 'Household', sort_order: 1).empty?
    @sections = CustomSection.where('model_type = ? AND sort_order > ?', 'Household', 1)
    @person_custom_fields = CustomField.where(model_type: 'Person')
  end

  # POST /households
  def create
    @household = Household.new(household_params)
    @custom_fields = CustomField.where(model_type: "Household")

    if @household.save
      if params[:custom_fields].present? && @custom_fields.length > 0
        CustomFieldGroup.create_or_update(@household, @custom_fields, params_for_custom_field)
      end

      respond_to do |format|
        format.html {redirect_to household_path(@household), notice: t("action_messages.create", model: Household.model_name.human)}
        format.js
      end
    else
      render :new
    end
  end

  # PATCH/PUT /households/1
  def update
    @custom_fields = CustomField.where(model_type: "Household")

    if @household.update_attributes(household_params)
      if params[:custom_fields].present? && @custom_fields.length > 0
        CustomFieldGroup.create_or_update(@household, @custom_fields, params_for_custom_field)
      end

      redirect_to household_path(@household), notice: t("action_messages.update", model: Household.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /households/1
  def destroy
    @household.destroy
    redirect_to households_path(), notice: t("action_messages.destroy", model: Household.model_name.human)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.first
    end

    def set_household
      @household = Household.find(params[:id])
    end

    def set_regions
      @regions = Region.all
    end

    # Only allow a trusted parameter "white list" through.
    def household_params
      params.require(:household).permit(
        :name, :code, :intake_date, :address_line_1, :address_line_2,
        :postal_code, :dependent_locality, :locality, :adminv_area,
        :dependent_adminv_area, :country, :address_info,
        people_attributes: [:intake_date, :first_name, :last_name,
          :middle_name, :sex, :dob, :relationship_id, :is_beneficiary,
          :_destroy, :id],
        income_sources_attributes: [:name, :estimated_volume_produced,
          :estimated_volume_sold, :unit_of_measure, :estimated_income,
          :currency, :_destroy, :id]
      )
    end

    def params_for_custom_field
      params.require(:custom_fields)
    end
end

app/helpers/households_helper.rb
module HouseholdsHelper
  def head_of_household adult
    if adult.is_head_of_household
      parts =[
        '<span class="fa fa-h-square" aria-hidden="true" ',
        'data-toggle="tooltip" data-placement="right" title="',
        Adult.human_attribute_name(:is_head_of_household),
        '"></span><span class="sr-only">',
        Adult.human_attribute_name(:is_head_of_household),
        '</span>'
      ]

      raw parts.join
    end
  end

  def household_or_households_path household
    if household.id
      household_path household
    else
      households_path
    end
  end
end

app/views/households/_adult_fields.html.erb
<fieldset class="associated-fields">
  <div class="form-group">
    <%= f.label :fname %>
    <%= f.text_field :fname, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lname %>
    <%= f.text_field :lname, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :mname %>
    <%= f.text_field :mname, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :sex %>
    <div class="checkbox">
      <% Adult::SEX_OPTIONS.each do |sex_option| %>
        <label class="radio-inline">
          <%= f.radio_button :sex, sex_option[1], class: "square-red" %> <%= t(sex_option[0]) %>
        </label>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :dob %> (yyy/mm/dd)
    <div class="input-group date">
      <%= f.text_field :dob, class: "form-control" %>
      <span class="input-group-addon">
        <i class="fa fa-calendar"></i>
      </span>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_head_of_household do %>
      <%= f.check_box :is_head_of_household, class: "square-red" %>
      <%= Adult.human_attribute_name :is_head_of_household %>
    <% end %>
  </div>

  <%= f.hidden_field :_destroy %>
  <%= link_to '#', class: "remove_fields pull-right" do %>
    <i class="fa fa-trash-o"></i><%= t("general.delete") %>
  <% end %>
</fieldset>
<hr>

app/views/households/_form.html.erb
<%= form_for([@household], html: { role: "form" }) do |f| %>
<%= error_messages(@household) %>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "info" %>
    <h3 class="box-title">
      <%= t("households.new.details_title") %>
    </h3>
  </div>
  <div class="box-body">
    <div class="form-group">
      <%= f.label :intake_date %>
      <div class="row date-select">
        <%= f.date_select :intake_date, {order: [:month, :day, :year]},
          {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address_line_1 %>
      <%= f.text_field :address_line_1, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address_line_2 %>
      <%= f.text_field :address_line_2, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :dependent_locality %>
      <%= f.text_field :dependent_locality, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :locality %>
      <%= f.text_field :locality, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :dependent_adminv_area %>
      <%= f.text_field :dependent_adminv_area, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :adminv_area %>
      <%= f.text_field :adminv_area, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :country %>
      <%= f.text_field :country, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address_info %>
      <%= f.text_area :address_info, rows: 5, class: "form-control" %>
    </div>

    <%= render partial: 'custom_fields/custom_field',
      collection: @section_1_custom_fields,
      locals: {model_id: @household.id} %>

  </div>
</div>

<%= render partial: 'custom_sections/custom_section',
  collection: @sections, locals: {model_id: @household.id} %>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "money" %>
    <h3 class="box-title">
      <%= IncomeSource.model_name.human.pluralize %>
    </h3>
  </div>
  <div class="box-body">
    <table class="table table-hover table-condensed">
      <thead>
      <tr>
        <th>
          <%= IncomeSource.human_attribute_name :name %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :estimated_volume_produced %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :estimated_volume_sold %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :unit_of_measure %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :estimated_income %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :currency %>
        </th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
        <%= f.fields_for :income_sources do |builder| %>
          <%= render 'income_source_fields', f: builder %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td>
            <%= link_to_add_fields t("income_source.index.add"), f,
              :income_sources, class: "add_fields btn btn-primary" %>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

<%= submit_or_cancel household_or_households_path(@household) %>
<% end %>

app/views/households/_household.html.erb
<tr>
  <td><%= link_to household.id, household_path(household) %></td>
  <td><%= link_to household.name, household_path(household) %></td>
  <td><%= household.children.count %></td>
  <td><%= household.adults.count %></td>
  <td><%= household.intake_date %></td>
</tr>

app/views/households/_income_source.html.erb
<tr>
  <td><%= income_source.name %></td>
  <td><%= income_source.estimated_volume_produced %></td>
  <td><%= income_source.estimated_volume_sold %></td>
  <td><%= income_source.unit_of_measure %></td>
  <td><%= income_source.estimated_income %></td>
  <td><%= income_source.currency %></td>
</tr>

app/views/households/_income_source_fields.html.erb
<tr class="associated-fields">
  <td>
    <%= f.text_field :name, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :estimated_volume_produced, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :estimated_volume_sold, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :unit_of_measure, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :estimated_income, class: "form-control" %>
  </td>
  <td>
    <%= f.text_field :currency, class: "form-control" %>
  </td>
  <td>
    <%= f.hidden_field :_destroy %>
    <%= link_to '#', class: "remove_fields btn" do %>
      <%= fa_icon 'trash-o', text: t('general.delete') %>
    <% end %>
  </td>
</tr>

app/views/households/_person.html.erb
<tr>
  <td>
    <%= link_to person.id, household_person_path(@household, person) %>
  </td>
  <td>
    <%= link_to person.last_name, household_person_path(@household, person) %>
  </td>
  <td>
    <%= person.first_name %>
  </td>
  <td>
    <%= person.age %>
  </td>
  <td>
    <%= person.gender_name %>
  </td>
  <td>
    <%= person.intake_work_status&.name %>
  </td>
</tr>

app/views/households/edit.html.erb
<% title t('households.edit.title') %>

<div class="page-header">
 <%= link_to households_path(), class: 'btn btn-default' do %>
    <%= fa_icon 'caret-left', text: t("general.back") %>
  <% end %>
  <%= link_to household_path(@household), class: 'btn btn-primary' do %>
    <%= fa_icon "info-circle", text: t("general.show") %>
  <% end %>
</div>

<%= render 'form' %>

app/views/households/index.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "home" %>
    <h3 class="box-title"><%= t("households.index.title") %></h3>
    <div class="box-tools">
      <%= link_to new_household_path, class: "btn btn-primary btn-sm" do %>
        <%= fa_icon 'plus', text: t('households.index.add') %>
      <% end %>
      <%= link_to households_path(format: :xlsx),
        class: 'btn btn-primary btn-sm' do %>
        <%= fa_icon 'file-excel-o', text: t('households.index.export') %>
      <% end %>
    </div>
  </div>
  <div class="box-body">
    <table id="households-data-table"
      class="table table-hover table-condensed">
      <thead>
        <tr>
          <th><%= Household.human_attribute_name(:id) %></th>
          <th><%= Household.human_attribute_name(:name) %></th>
          <th><%= Household.human_attribute_name(:children) %></th>
          <th><%= Household.human_attribute_name(:adults) %></th>
          <th><%= Household.human_attribute_name(:intake_date) %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "household", collection: @households %>
      </tbody>
    </table>
  </div>
</div>

app/views/households/new.html.erb
<% title t('households.new.title') %>
<%= render 'form' %>

app/views/households/show.html.erb
<% title @household.name %>
<% description "#{@household.intake_date}" %>

<div class="page-header">
  <%= link_to households_path, class: 'btn btn-default' do %>
    <%= fa_icon 'caret-left', text: t('general.back') %>
  <% end %>
  <%= link_to edit_household_path(@household),
    class: 'btn btn-primary' do %>
    <%= fa_icon 'pencil', text: t('general.edit') %>
  <% end %>
</div>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "info" %>
    <h3 class="box-title">
      <%= t("households.show.title") %>
    </h3>
  </div>
  <div class="box-body">
    <table class="table table-hover table-listing table-condensed">
      <tbody>
        <tr>
          <th><%= Household.human_attribute_name(:id) %></th>
          <td><%= @household.id %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:name) %></th>
          <td><%= @household.name %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:intake_date) %></th>
          <td><%= @household.intake_date %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:address_line_1) %></th>
          <td><%= @household.address_line_1 %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:address_line_2) %></th>
          <td><%= @household.address_line_2 %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:dependent_locality) %></th>
          <td><%= @household.dependent_locality %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:locality) %></th>
          <td><%= @household.locality %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:dependent_adminv_area) %></th>
          <td><%= @household.dependent_adminv_area %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:adminv_area) %></th>
          <td><%= @household.adminv_area %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:postal_code) %></th>
          <td><%= @household.postal_code %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:country) %></th>
          <td><%= @household.country %></td>
        </tr>
        <tr>
          <th><%= Household.human_attribute_name(:address_info) %></th>
          <td><%= @household.address_info %></td>
        </tr>
        <tr>
        <% @section_1_custom_fields.each do |custom_field| %>
        </tr>
        <tr>
          <th><%= custom_field.name %></th>
          <td><%= custom_field_display(custom_field, @household.id) %></td>
        </tr>
        <% end unless @section_1_custom_fields.nil? %>
      </tbody>
    </table>
  </div>
</div>

<%= render partial: 'custom_sections/custom_section_show',
  collection: @sections, locals: {model_id: @household.id} %>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "money" %>
    <h3 class="box-title">
      <%= IncomeSource.model_name.human.pluralize %>
    </h3>
  </div>
  <div class="box-body">
    <table class="table table-condensed table-hover">
      <thead>
      <tr>
        <th>
          <%= IncomeSource.human_attribute_name :name %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :estimated_volume_produced %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :estimated_volume_sold %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :unit_of_measure %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :estimated_income %>
        </th>
        <th>
          <%= IncomeSource.human_attribute_name :currency %>
        </th>
      </tr>
      </thead>
      <tbody>
        <%= render partial: "income_source",
          collection: @household.income_sources %>
      </tbody>
    </table>
  </div>
</div>

<div class="box box-primary">
  <div class="box-header with-border">
    <%= fa_icon "users" %>
    <h3 class="box-title">
      <%= Person.model_name.human.pluralize %>
    </div>
    <div class="box-body">
      <table id="people-data-table"
        class="table table-condensed table-hover">
        <thead>
          <tr>
            <th><%= Person.human_attribute_name :id %></th>
            <th><%= Person.human_attribute_name :last_name %></th>
            <th><%= Person.human_attribute_name :first_name %></th>
            <th><%= Person.human_attribute_name :age %></th>
            <th><%= Person.human_attribute_name :sex %></th>
            <th><%= Person.human_attribute_name :intake_status %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "person",
            collection: @household.people.order(:id) %>
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <%= link_to new_household_person_path(@household),
        class: "btn btn-primary" do %>
        <%= fa_icon 'plus', text: t('households.index.add_member') %>
      <% end %>
    </div>
  </div>
</div>